# Generated by Django 3.1.1 on 2020-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(),
        ),
    ]
