
from django.urls import path, include
from . import views
from . import HodViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_teacher/', HodViews.add_teacher, name="add_teacher"),
    path('add_teacher_save/', HodViews.add_teacher_save, name="add_teacher_save"),
    path('add_semister/', HodViews.add_semister, name="add_semister"),
    path('add_semister_save/', HodViews.add_semister_save, name="add_semister_save"),
    path('add_student/', HodViews.add_student, name="add_student"),
    path('add_student_save/', HodViews.add_student_save, name="add_student_save"),
    path('attendance_student/', HodViews.attendance_student, name="attendance_student"),
    path('attendance_faculty/', HodViews.attendance_faculty, name="attendance_faculty"),
    path('change_password/',views.change_password, name='change_password'),
    path('check_email/', views.go_here, name ="go_here"),
    path('checked_email/', views.reset_password , name="reset_password"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('delete_semister/<semister_id>/', HodViews.delete_semister, name="delete_semister"),
    path('edit_semister/<semister_id>/', HodViews.edit_semister, name="edit_semister"),
    path('edit_semister_save/', HodViews.edit_semister_save, name="edit_semister_save"),
    path('edit_teacher/<teacher_id>/', HodViews.edit_teacher, name="edit_teacher"),
    path('edit_teacher_save/', HodViews.edit_teacher_save, name="edit_teacher_save"),
    path('delete_teacher/<teacher_id>/', HodViews.delete_teacher, name="delete_teacher"), 
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('leave_req/', HodViews.leave_req, name="leave_req"),
    path('leave_req_faculty/', HodViews.leave_req_faculty, name="leave_req_faculty"), 
    path('manage_semister/', HodViews.manage_semister, name="manage_semister"),
    path('manage_teacher/', HodViews.manage_teacher, name="manage_teacher"),
    path('manage_student/', HodViews.manage_student, name="manage_student"),
    path('send_otp/' , views.sending_email , name="sending_email"),
    path('successful/', views.verify_otp , name="verify_otp"),
    path('show_calendar/' , HodViews.show_calendar , name='show_calendar'),
    path('staff_home/', HodViews.staff_home, name="staff_home"),
    path('student_home/', HodViews.student_home, name="student_home"),
    # path('edit_student/<student_id>', HodViews.edit_student, name="edit_student"),
    # path('edit_student_save/', HodViews.edit_student_save, name="edit_student_save"),
    # path('delete_student/<student_id>/', HodViews.delete_student, name="delete_student"),
    path(r'new_event/',HodViews.new_event , name='new_event_adder'),
]
